name: Bug Report
description: Is something broken? Make it known!
title: "[Bug]"
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: Before Reporting
    description: "I have double checked and agree with the following:"
    options:
    - label: I found no existing matching issue
      required: true
    - label: This is not a support request
      required: true
    - label: My skin is up-to-date
      required: true
- type: textarea
  attributes:
    label: Describe the Problem
    description: A clear and concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: upload
  attributes:
    label: Upload Screenshots
    description: If applicable, add screenshots to show your problem. These really help!
  validations:
    required: false