blank_issues_enabled: false
contact_links:
  - name: Support Forum
    url: https://github.com/yurisuika/Zehn/discussions/categories/support
    about: Confused or confuddled? Have your questions answered!