name: Feature Request
description: Propose a feature to improve Zehn!
title: "[Feature]"
labels: [enhancement]
body:
- type: checkboxes
  attributes:
    label: Before Requesting
    description: "I have double checked and agree with the following:"
    options:
    - label: I found no existing matching issue
      required: true
- type: textarea
  attributes:
    label: Describe the feature you'd like!
    description: A clear and detailed description of what you want to see in Zehn.
  validations:
    required: true
- type: upload
  attributes:
    label: Upload Screenshots
    description: If applicable, add screenshots to show where your proposed feature would affect.
  validations:
    required: false