name: Feature Request
description: Propose a feature for Zehn! This is for detailed proposals; for suggestions, use Discussions instead.
title: "[Feature]"
labels: [enhancement]
body:
- type: checkboxes
  attributes:
    label: Before Requesting
    description: "I have checked that the following are true:"
    options:
    - label: There is no existing matching issue or discussion.
      required: true
    - label: My theme is up-to-date.
      required: true
- type: textarea
  attributes:
    label: Describe the feature you'd like!
    description: A clear and detailed description of what you want to see in Zehn.
  validations:
    required: true
- type: upload
  attributes:
    label: Upload Screenshots
    description: If applicable, add screenshots to show where your proposed feature would affect.
  validations:
    required: false