name: Create Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y.%-m.%-d')" >> $GITHUB_OUTPUT
      - uses: actions/checkout@master
      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          directory: "."
          path: "."
          type: 'zip'
          custom: -r
          filename: 'zehn-${{ steps.date.outputs.DATE }}.zip'
          exclusions: '*.git* /assets* README.md CNAME'
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: true
          commit: master
          name: ${{ steps.date.outputs.date }}
          tag: ${{ steps.date.outputs.date }}
          artifacts: "*.zip"
          body: "Latest builds as of ${{ steps.date.outputs.date }}."