name: Create Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y.%-m.%-d')" >> $GITHUB_OUTPUT
      - uses: actions/checkout@master
      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.6
        env:
          DATE: ${{ steps.date.outputs.DATE }}
        with:
          directory: "./static"
          type: 'zip'
          filename: 'zehn-$DATE.zip'
      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.6
        env:
          DATE: ${{ steps.date.outputs.DATE }}
        with:
          directory: "./live"
          type: 'zip'
          filename: 'zehn-live-$DATE.zip'
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          DATE: ${{ steps.date.outputs.DATE }}
        with:
          allowUpdates: true
          replacesArtifacts: true
          commit: master
          name: ${{ steps.date.outputs.date }}
          tag: ${{ steps.date.outputs.date }}
          artifacts: "zehn-$DATE.zip,zehn-live-$DATE.zip"