name: Create Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%-m.%-d')"
      - uses: actions/checkout@master
      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          directory: "./static"
          type: 'zip'
          filename: 'zehn-${{ steps.date.outputs.date }}.zip'
      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          directory: "./live"
          type: 'zip'
          filename: 'zehn-live-${{ steps.date.outputs.date }}.zip'
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: true
          name: ${{ steps.date.outputs.date }}
          tag: ${{ steps.date.outputs.date }}
          artifacts: "*"